steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/container-web-app-433406/cloud-run-source-deploy', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/container-web-app-433406/cloud-run-source-deploy']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'blue-screen-app', '--image', 'gcr.io/container-web-app-433406/cloud-run-source-deploy', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
images:
  - 'gcr.io/container-web-app-433406/cloud-run-source-deploy'
